trigger:
- main

pool:
  name: MylocalPool

stages:
- stage: TriggerLambdaTest
  displayName: "Trigger LambdaTest HyperExecute Job"
  jobs:
  - job: RunLambdaTestCurl
    displayName: "Execute LambdaTest HyperExecute API"
    steps:
      - script: |
          echo "Triggering LambdaTest HyperExecute Test Run..."
          curl -X POST "https://test-manager-api.lambdatest.com/api/atm/v1/hyperexecute" \
          -H "Content-Type: application/json" \
          -H "Authorization: Basic cHJpeWFuc2h1ZzpMVF9JNXphSnB2S2I5dG1wWGtpNWh0cDQ5SGVWejg1NWoxQ2pXSFA3YzB0RnR6NVlhag==" \
          -d '{"test_run_id":"01KTV7VQPRAFPY99KDYYZT1294","concurrency":1}'
        displayName: "Run LambdaTest HyperExecute via cURL"